### ISSUE TITLE
Crashes sm64 compressor when i compress the extended ROM

### ISSUE THREAD

**Issue by Eddio0141** [queueRAM/sm64tools#2]
Simply, i used the extender and it made an 64MB ROM file.
I've tried compressing it directly without changing anything in the ROM and it crashes after the "count : 135" output. 
No arguments are used in both extender and compressor.

**Comment by queueRAM** [comment]
Indeed, you are correct! sm64compress was intended to run after using SM64 Editor which breaks some more things, so I had some assumptions in there. I'll commit a fix here shortly.

**Comment by David190504** [comment]
Sorry for probably bothering to any of you but I have the same issue. Is there a solution or something I've done wrong? (I just expanded the rom to 64 MB, applied some tweaks in SM64 Editor and tried to compress it with the tool).

**Comment by queueRAM** [comment]
This was fixed in 524c6d7

**Comment by Retrorezzie** [comment]
How do I add the new code  to sm64compress
